routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

Route::middleware('guest:admin')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('perform-login');
});

Route::middleware('auth:admin')->group(function () {
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::group(['active_item' => 'departments'], function () {
        Route::resource('departments', 'DepartmentController');

        Route::post('departments/{department}/import', 'DepartmentController@import')
             ->name('departments.import');

        Route::resource('departments.subjects', 'SubjectController')->except([
            'index', 'show'
        ])->shallow();
    });

    Route::group(['active_item' => 'questions'], function () {
        Route::resource('questions', 'QuestionController')->except('show');
    });

    Route::group(['active_item' => 'teachers'], function () {
        Route::resource('teachers', 'TeacherController');
    });

    Route::group(['active_item' => 'codes'], function () {
        Route::resource('departments.codes', 'CodeController')->only(
            'index', 'create', 'store'
        )->shallow();

        Route::get('/departments/{department}/codes/{semester}/print', 'CodeController@print')
             ->name('codes.print');

        Route::get('/departments/codes/first', 'CodeController@first')
             ->name('departments.codes.first');

        Route::post('/codes/publish', 'CodeController@publish')
            ->name('codes.publish');

        Route::post('/codes/hide', 'CodeController@hide')
            ->name('codes.hide');
    });

    Route::group(['active_item' => 'reports'], function () {
        Route::resource('reports', 'ReportController')
            ->only('index', 'show', 'store');

        Route::delete('/reports', 'ReportController@reset')
             ->name('reports.reset')
             ->middleware('password_protected');

        Route::delete('/reports/archive', 'ReportController@destroy')
             ->name('reports.archive')
             ->middleware('password_protected');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Route::get('/codes', 'CodesController@index')->name('codes.index');
Route::get('/codes/{department}', 'CodesController@show')->name('codes.show');

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::middleware('auth:web')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('/survey/begin', 'SurveyController@index')->name('survey.index');
    Route::get('/survey/take/{question}', 'SurveyController@show')->name('survey.show');
    Route::post('/survey/{question}/store', 'SurveyController@store')->name('survey.store');
    Route::get('/survey/complete', 'SurveyController@complete')->name('survey.complete');
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable = [
        'name', 'semester', 'teacher_id', 'assistant_id'
    ];

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function teacher()
    {
        return $this->belongsTo(Teacher::class, 'teacher_id');
    }

    public function assistant()
    {
        return $this->belongsTo(Teacher::class, 'assistant_id');
    }
}

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\SubjectRequest;
use App\Models\Department;
use App\Models\Subject;
use App\Models\Teacher;

class SubjectController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Department $department)
    {
        $subject = new Subject();
        $subject->department = $department;
        $teachers = $this->prepareTeacherOptions();

        return view('admin.subjects.create', compact('subject', 'department', 'teachers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Admin\SubjectRequest $request
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SubjectRequest $request, Department $department)
    {
        $subject = Subject::make($request->validated());
        $subject->department_id = $department->id;

        $subject->save();

        return redirect()->route('admin.departments.show', ['department' => $department->id])->with('success', 'Predmet uspešno dodat.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Subject $subject
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Subject $subject)
    {
        $teachers = $this->prepareTeacherOptions();

        return view('admin.subjects.edit', compact('subject', 'teachers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Admin\SubjectRequest $request
     * @param \App\Models\Subject $subject
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SubjectRequest $request, Subject $subject)
    {
        $subject->update($request->validated());

        return redirect()->route('admin.departments.show', $subject->department_id)->with('success', 'Predmet uspešno izmenjen.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Subject $subject
     * @return void
     */
    public function destroy(Subject $subject)
    {
        $subject->delete();

        return redirect()->route('admin.departments.show', $subject->department_id)->with('success', 'Predmet uspešno izbrisan.');
    }

    /**
     * @return array
     */
    protected function prepareTeacherOptions()
    {
        return Teacher::all()->mapWithKeys(function (Teacher $teacher) {
            return [$teacher->id => $teacher->name];
        })->sort()->toArray();
    }
}

resources/views/admin/subjects/create.blade.php
@extends('layouts.admin')

@section('title', 'Додај предмет')

@section('content')
    <div class="container">
        <div class="h1 text-center">
            Додај предмет
        </div>

        <div class="row justify-content-center">
            <div class="col-md-8 mt-5">
                <form method="POST"action="{{ route('admin.departments.subjects.store', $department->id) }}">
                    @csrf

                    @include('admin.subjects.partials.fields')

                    <div class="d-flex justify-content-center">
                        @include('admin.partials.form_actions', [
                            'submitCta' => 'Додај',
                            'cancelUrl' => route('admin.departments.show', $department->id),
                            'cancelCta' => 'Откажи',
                        ])
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/subjects/edit.blade.php
@extends('layouts.admin')

@section('title', "Измени {$subject->name}")

@section('content')
    <div class="container">
            <div class="h1 text-center">
                {{ $subject->name }}
            </div>

            <div class="row justify-content-center">
                <div class="col-md-8 mt-5">
                    <form method="POST" action="{{ route('admin.subjects.update', $subject->id) }}">
                        @csrf
                        @method('PATCH')

                        @include('admin.subjects.partials.fields')

                        <div class="d-flex justify-content-center">
                            @include('admin.partials.form_actions', [
                            'submitCta' => 'Сачувај',
                            'cancelUrl' => route('admin.departments.show', $subject->department_id),
                            'cancelCta' => 'Откажи',
                            ])
                        </div>
                    </form>
                </div>
            </div>
    </div>
@endsection