routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

Route::middleware('guest:admin')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('perform-login');
});

Route::middleware('auth:admin')->group(function () {
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::group(['active_item' => 'departments'], function () {
        Route::resource('departments', 'DepartmentController');

        Route::post('departments/{department}/import', 'DepartmentController@import')
             ->name('departments.import');

        Route::resource('departments.subjects', 'SubjectController')->except([
            'index', 'show'
        ])->shallow();
    });

    Route::group(['active_item' => 'questions'], function () {
        Route::resource('questions', 'QuestionController')->except('show');
    });

    Route::group(['active_item' => 'teachers'], function () {
        Route::resource('teachers', 'TeacherController');
    });

    Route::group(['active_item' => 'codes'], function () {
        Route::resource('departments.codes', 'CodeController')->only(
            'index', 'create', 'store'
        )->shallow();

        Route::get('/departments/{department}/codes/{semester}/print', 'CodeController@print')
             ->name('codes.print');

        Route::get('/departments/codes/first', 'CodeController@first')
             ->name('departments.codes.first');

        Route::post('/codes/publish', 'CodeController@publish')
            ->name('codes.publish');

        Route::post('/codes/hide', 'CodeController@hide')
            ->name('codes.hide');
    });

    Route::group(['active_item' => 'reports'], function () {
        Route::resource('reports', 'ReportController')
            ->only('index', 'show', 'store');

        Route::delete('/reports', 'ReportController@reset')
             ->name('reports.reset')
             ->middleware('password_protected');

        Route::delete('/reports/archive', 'ReportController@destroy')
             ->name('reports.archive')
             ->middleware('password_protected');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Route::get('/codes', 'CodesController@index')->name('codes.index');
Route::get('/codes/{department}', 'CodesController@show')->name('codes.show');

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::middleware('auth:web')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('/survey/begin', 'SurveyController@index')->name('survey.index');
    Route::get('/survey/take/{question}', 'SurveyController@show')->name('survey.show');
    Route::post('/survey/{question}/store', 'SurveyController@store')->name('survey.store');
    Route::get('/survey/complete', 'SurveyController@complete')->name('survey.complete');
});

app/Models/Code.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Code extends Authenticatable
{
    const CODES_PUBLIC_SETTING = 'codes-public';

    protected $fillable = [
        'code', 'semester'
    ];

    protected $with = [
        'department.subjects.teacher', 'department.subjects.assistant',
    ];

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function getAuthIdentifierName()
    {
        return 'code';
    }

    public function scopeAvailable(Builder $query)
    {
        $query->where('codes.used', false);
    }

    public function scopeUsed(Builder $query)
    {
        $query->where('codes.used', true);
    }

    public function scopeForSemester(Builder $query, $semester)
    {
        return $query->where('semester', $semester);
    }
}

app/Http/Controllers/Admin/CodeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CodeRequest;
use App\Jobs\GenerateCodes;
use App\Models\Code;
use App\Models\Department;
use App\Models\Settings;

class CodeController extends Controller
{
    /**
     * Route used for the admin navigation bar.
     * Redirects to the first department's codes page.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function first()
    {
        return redirect()->route('admin.departments.codes.index', Department::firstOrFail()->id);
    }

    /**
     * Display a listing of the resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Department $department)
    {
        $codes = $department->codes()
                            ->orderBy('semester')
                            ->orderBy('code')
                            ->available()
                            ->get()
                            ->groupBy('semester');

        $totalAvailableCodes = $department->codes()->available()->count();
        $totalUsedCodes = $department->codes()->used()->count();

        $departments = Department::all();

        return view('admin.codes.index', compact(
            'department',
            'departments',
            'codes',
            'totalAvailableCodes',
            'totalUsedCodes'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Department $department)
    {
        $departments = Department::orderBy('name')
                                 ->get()
                                 ->mapWithKeys(function (Department $department) {
                                     return [$department->id => $department->name];
                                 });

        return view('admin.codes.create', compact('department'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Admin\CodeRequest $request
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CodeRequest $request, Department $department)
    {
        GenerateCodes::dispatch(
            $department,
            $request->get('semester'),
            $request->get('batch')
        );

        return redirect()->route('admin.departments.codes.index', $department->id)->with('success', 'Kodovi uspešno generisani');
    }

    public function publish()
    {
        Settings::set(Code::CODES_PUBLIC_SETTING, true);

        return redirect()->back()
            ->with('success', 'Страница са кодовима је објављена.');
    }

    public function hide()
    {
        Settings::set(Code::CODES_PUBLIC_SETTING, false);

        return redirect()->back()
            ->with('success', 'Страница са кодовима је сакривена.');
    }

    /**
     * @param \App\Models\Department $department
     * @param $semester
     * @return \Illuminate\View\View
     */
    public function print(Department $department, $semester)
    {
        return view('admin.codes.print', [
            'department' => $department,
            'semester' => $semester,
            'codes' => $department->codes()->forSemester($semester)->get(),
        ]);
    }
}

app/Http/Controllers/CodesController.php
<?php

namespace App\Http\Controllers;

use App\Facades\UserSurvey;
use App\Models\Code;
use App\Models\Department;
use App\Models\Settings;
use Illuminate\Support\Facades\Auth;

class CodesController extends Controller
{
    public function index()
    {
        if (Auth::user() && UserSurvey::isOngoing()) {
            return UserSurvey::redirectToNextQuestion();
        }

        if (!Settings::get(Code::CODES_PUBLIC_SETTING)) {
            return redirect()->route('home');
        }

        return redirect()->route('codes.show', Department::first());
    }

    public function show(Department $department)
    {
        if (Auth::user() && UserSurvey::isOngoing()) {
            return UserSurvey::redirectToNextQuestion();
        }

        if (!Settings::get(Code::CODES_PUBLIC_SETTING)) {
            return redirect()->route('home');
        }

        $codes = $department->codes()
                            ->available()
                            ->orderBy('semester', 'asc')
                            ->get()
                            ->groupBy('semester');

        return view('codes', [
            'departmentCodes' => $codes,
            'department' => $department,
            'departments' => Department::all(),
        ]);
    }
}

resources/views/admin/codes/create.blade.php
@extends('layouts.admin')

@section('title', 'Генериши кодове')

@section('content')
    <div class="container">
        <div class="h1 text-center">
            Генериши кодове
        </div>

        <div class="row justify-content-center">
            <div class="col-md-8 mt-5">
                <form method="POST"action="{{ route('admin.departments.codes.store', $department->id) }}">
                    @csrf

                    @include('admin.codes.partials.fields')

                    <div class="d-flex justify-content-center">
                        @include('admin.partials.form_actions', [
                            'submitCta' => 'Генериши',
                            'cancelUrl' => route('admin.departments.codes.index', $department->id),
                            'cancelCta' => 'Откажи',
                        ])
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/codes/index.blade.php
@extends('layouts.admin')

@section('title', 'Кодови')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-2">
                @include('admin.departments.navigation', ['departments' => $departments, 'activeDepartment' => $department->id, 'routeLink' => 'admin.departments.codes.index'])
            </div>

            <div class="col-md-10">
                <div class="d-flex justify-content-between mb-3">
                    <div>
                        Број неискоришћених кодова за смер: {{ $totalAvailableCodes }}
                        <br>
                        Број искоришћених кодова за смер: {{ $totalUsedCodes }}
                    </div>
                    <div class="d-flex  justify-content-end">
                        <form>
                            <a class="btn btn-secondary mr-1" href="{{ route('admin.departments.codes.create', $department->id) }}">Генериши кодове</a>
                        </form>

                        @if(Settings::get('codes-public'))
                            <form action="{{ route('admin.codes.hide') }}" method="post">
                                @csrf

                                <button type="submit" class="btn btn-secondary">Сакриј кодове</button>
                            </form>
                        @else
                            <form action="{{ route('admin.codes.publish') }}" method="post">
                                @csrf

                                <button type="submit" class="btn btn-secondary">Објави кодове</button>
                            </form>
                        @endif
                    </div>
                </div>

                <ul class="nav nav-tabs" id="semesters" role="tablist">
                    @foreach ($codes as $semester => $semesterCodes)
                        <li class="nav-item">
                            <a
                                    class="nav-link @if($loop->first) active @endif "
                                    id="{{ $semester }}-tab"
                                    data-toggle="tab"
                                    href="#semester-{{ $semester }}"
                                    role="tab"
                                    aria-controls="semester-{{ $semester }}"
                                    @if ($loop->first)
                                    aria-selected="true"
                                    @endif
                            >{{ $semester }}. семестар</a>
                        </li>
                    @endforeach
                </ul>
                <div class="tab-content mt-4">
                    @foreach ($codes as $semester => $semesterCodes)
                        <div class="tab-pane @if($loop->first) active @endif" id="semester-{{ $semester }}" role="tabpanel" aria-labelledby="{{ $semester }}-tab">
                            <div class="d-flex justify-content-between mb-2">
                                <div>
                                    Број неискоришћених кодова за {{ $semester }}. семестар: {{ $semesterCodes->where('used', false)->count() }}
                                    <br>
                                    Број искоришћених кодова за {{ $semester }}. семестар: {{ $semesterCodes->where('used', true)->count() }}
                                </div>
                                <a
                                    href="{{ route('admin.codes.print', ['department' => $department, 'semester' => $semester]) }}"
                                    target="_blank"
                                    class="btn btn-secondary">
                                    Одштампај кодове за {{ $semester }}. семестар
                                </a>
                            </div>
                            <table class="table">
                                <thead class="thead-dark">
                                    <th scope="col">
                                        Код
                                    </th>
                                    <th scope="col">
                                        Смер
                                    </th>
                                    <th scope="col">
                                        Семестар
                                    </th>
                                </thead>
                                <tbody>
                                    @foreach ($semesterCodes as $code)
                                        <tr>
                                            <th class="align-middle" scope="row">{{ $code->code }}</th>
                                            <td class="align-middle">{{ $department->name }}</td>
                                            <td class="align-middle">{{ $semester  }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endforeach
                </div>

                @if ($codes->isEmpty())
                    <div class="h2 text-center">
                        Нема неупотребљених кодова
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/admin/codes/print.blade.php
@foreach($codes->chunk(100) as $pageCodes)
    <table style="width: 95%; margin: auto; border-collapse: collapse;" border="1px solid black">
        <thead>
            <tr>
                <th colspan="4" style="font-size: 40px">
                    {{ $department->shorthand }} - {{ $semester }}. семестар
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($pageCodes->chunk(4) as $rowCodes)
                <tr>
                    @for($i = 0; $i < 4; $i++)
                        <td align="center" style="font-size: 23px">
                            {{ optional($rowCodes->values()->get($i))->code }}
                        </td>
                    @endfor
                </tr>
            @endforeach
        </tbody>
    </table>
    <div style="page-break-after: always"></div>
@endforeach
<script>
    window.print();
    window.onfocus = () => { window.close(); }
</script>